### ISSUE TITLE
COMPONENT - Tabs Container

### ISSUE THREAD

**Issue by MichaelFriel** [GroupOneProject/Track-City#17]
**Updated Ticket**

We may now be using ant.design to create this, as it has an add button. 

**Acceptance Criteria**

- Container which includes an 'add new tab' function.
- The content for this component will be made separately, so this will just link to the imported component.

---------
Old information below for posterity
---------

We need components for Tabs and Tab content. These can be sourced from MUI for the most part:

https://mui.com/material-ui/react-tabs/

**Acceptance Criteria**

- User needs to be able to hit a plus icon to add a new tracker.
- New trackers should be added to the tabs array, with a dynamic id representing the tab number.
- Once the tab is created, a function is initialised which gathers the user information and renders the content.
- Within that content function, they should also be able to add additional tasks to each tracker

**Comment by Antimio** [comment]
Done. @ToussaintPhillips, it seems, however, that the tables don't persist when we move to a different tab.
