### ISSUE TITLE
COMPONENT - Tabs Content

### ISSUE THREAD

**Issue by MichaelFriel** [GroupOneProject/Track-City#18]
We need to be able to dynamically generate content within the tabs component. This can either be done with React MUI, or with a Bootstrap table. 

**Acceptance Criteria**

- User inputs information, including: tab name, task 1 name, task 1 description, points, deadline.
- Add Task button to include additional tasks

https://mui.com/material-ui/react-table/

**Comment by ToussaintPhillips** [comment]
Tabs content table created which produces a dynamic table where task data can be inputted and data saved
