### ISSUE TITLE
Technical - Chart.js Research

### ISSUE THREAD

**Issue by MichaelFriel** [GroupOneProject/Track-City#4]
We need to review the documentation for chart.js and agree on an implementation approach. 

Some questions for consideration: 

- Will we be able to chart user points on a weekly basis?
- Will we be able to chart task completions on a weekly basis?

https://www.chartjs.org/docs/latest/charts/line.html

**Comment by minyyds** [comment]
- Will we be able to chart user points on a weekly basis?
   - Yes, you can make an array for the Days of the week and use those for the labels of the chart.
 
- Will we be able to chart task completions on a weekly basis?
   - Yes, data from the chart can be stored in an empty array, that data can be easily set using chart.js.
   
example image:
![image](https://github.com/GroupOneProject/Track-City/assets/151970835/29615880-fd31-436c-a7f8-844527cf8523)

**Comment by minyyds** [comment]
![Image](https://github.com/GroupOneProject/Track-City/assets/151970835/4fb713b1-e19e-448e-bca0-1b7272e462a7)

multiple lines for child competition 😡

**Comment by minyyds** [comment]
data can be set with the "data:" tag. this can be an empty array where points are stored and then can be set easily.
